### PR TITLE
Update contribution guideline.

### PR DESCRIPTION
**Pull request by eliasah**
I updated the contribution guideline to add the last commit status for each project contribution.

### CODE REVIEW

**Comment by zero323** [comment]
You should distinguish here between projects that are linked as GitHub repositories and other projects. Also, we might limit this only two software projects that are expected to be regularly updated.

**Comment by eliasah** [comment]
I'm not sure I actually get your point.

**Comment by zero323** [comment]
Badge makes sense if and only if the target is on GitHub. If you for example link to some MOOC platform, it will be meaningless.

Additionally some GitHub targets might not be regularly updated by design. Think for example of a companion repository to a paper book. Though to be fair this is probably not a serious concern.

**Comment by eliasah** [comment]
@zero323 up

**Comment by zero323** [comment]
__Add the link__ -> __If project provides a GitHub repository add link__.

**Pull request merged**
