### PR TITLE
Add itachi - General Purpose Libraries

### LINKED ISSUE #194: Consider yaooqinn / itachi
> itachi brings useful functions from modern database management systems to Apache Spark :)
>
> For example, you can import the Postgres extensions and write Spark code that looks just like Postgres.
>
> The functions are implemented as native Spark functions, so they're performant.

https://github.com/yaooqinn/itachi/

CC @yaooqinn @MrPowers

### PR DESCRIPTION
**Pull request by yaooqinn**
`itachi` is a library that brings excellent and useful functions from various modern database management systems to Apache Spark in the way of Code Generation

Github repo:
https://github.com/yaooqinn/itachi

closes #194

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @zero323 @MrPowers thanks

**Review by zero323 — COMMENTED** [review]
Could you add a dot at the end of the sentence, please?

**Comment by zero323** [comment]
Overall I am fine with adding the package. Any thoughts about the specific wording of entry @eliasah @oluies?

**Review by zero323 — APPROVED** [review]

**Comment by eliasah** [comment]
I like adding this library but I don't like the description. 
- Using the word "excellent" isn't very partial. 
- "in the way of Code Generation." I don't get it.

I'd rather we write : "A library that brings useful functions from modern database management systems to Apache Spark."

**Comment by yaooqinn** [comment]
thanks for the suggestions @eliasah

**Review by eliasah — APPROVED** [review]

**Comment by eliasah** [comment]
I'm sorry this was long guys (cc. @yaooqinn ) Thanks for the changes :)

**Pull request merged**
