### PR TITLE
Revert "Updated additional details about spark-csv lib"

### PR DESCRIPTION
**Pull request by zero323**
Reverts awesome-spark/awesome-spark#91

### CODE REVIEW

**Comment by eliasah** [comment]
what is wrong with that ?

**Comment by zero323** [comment]
@eliasah This needs more discussion. It sounds wrong and it is not accurate.

**Comment by eliasah** [comment]
Sure.

**Comment by eliasah** [comment]
What are your thought about it ?

**Comment by zero323** [comment]
You could explain that projects is discontinued and its functionality merged into main Spark repository but "inlined in ... artifact" doesn't sound right and is completely meaningless for Python or R users.

**Comment by eliasah** [comment]
Sure I'm sorry sometimes I forget about this inter-operabilities.

**Comment by zero323** [comment]
Maybe it should just "_obsolete since Spark 2.0 ([SPARK-12833](https://issues.apache.org/jira/browse/SPARK-12833))_"

**Comment by mrsrinivas** [comment]
@zero323 : can we go head and update as "obsolete since Spark 2.0" ?

**Comment by zero323** [comment]
@mrsrinivas Sure, please open another PR for this.

**Comment by eliasah** [comment]
I've already opened one https://github.com/awesome-spark/awesome-spark/pull/94

**Pull request merged**
