### PR TITLE
Optimus  Data Cleansing and Exploration utilities

### PR DESCRIPTION
**Pull request by oluies**
Intro post - https://www.linkedin.com/pulse/data-cleansing-exploration-new-era-optimus-favio-vázquez
Github - https://github.com/ironmussa/Optimus/ 

Demos seemed to work fine

### CODE REVIEW

**Comment by eliasah** [comment]
LGTM besides "Cleansing and Exploration" which I'd rather they are in lowercase

**Comment by eliasah** [comment]
What happened with this ?

**Comment by oluies** [comment]
Seemes to still be updated

**Comment by eliasah** [comment]
@oluies LGTM can you please fix the conflics so I can merge ? 
Thanks :)

**Comment by oluies** [comment]
oh shiny

**Pull request merged**
