### PR TITLE
[ADD] ML Workspace

### PR DESCRIPTION
**Pull request by LukasMasuch**

### CODE REVIEW

**Comment by oluies** [comment]
Looks ok with me @eliasah @zero323

**Comment by eliasah** [comment]
Me too @oluies :)

**Comment by zero323** [comment]
Thank you for your proposal @LukasMasuch . Are you still interested in merging this? 

If so, could you please update the PR (move proposal to the end of the list, drop no longer valid spark-flavor link).

**Comment by oluies** [comment]
Last commit  Nov 22, 2021

**Pull request closed without merging**
