### PR TITLE
#hbase-Connectors

### PR DESCRIPTION
**Pull request by oluies**

### CODE REVIEW

**Comment by eliasah** [comment]
I don't agree with hbase connectors having it's own section. 
https://github.com/Huawei-Spark/Spark-SQL-on-HBase doesn't seem to be active.

**Comment by oluies** [comment]
should we put them in the connectors section or not do anything

**Comment by zero323** [comment]
Both Phoenix and shc can be placed under SQL data sources.

**Comment by zero323** [comment]
@eliasah Would you mind adding closure reason?

**Comment by eliasah** [comment]
The same reason you gave. It can be placed under SQL data sources plus one of the projects is not active.

**Pull request closed without merging**
