### PR TITLE
Add photon-ml. Resolves #64.

### LINKED ISSUE #64: Add photon-ml
https://github.com/linkedin/photon-ml

@eliasah Would you do the honors?

### PR DESCRIPTION
**Pull request by eliasah**

### CODE REVIEW

**Comment by zero323** [comment]
Do we really need "based on Apache Spark"?

**Comment by eliasah** [comment]
Well I hasitated and I've added it. So not very sure !

**Comment by zero323** [comment]
Sometimes it is hard to avoid it but I don't think it is really required here. Also it would be cool to mention some of its features. It has really nice diagnostic tools which are missing from ML / MLlib. What you think?

**Comment by eliasah** [comment]
That's also something I had some doubt about. GLM, per example, don't exist in spark ml/mllib and they exist in sparkr...

**Comment by zero323** [comment]
I think formulas and stuff are scheduled for 2.1. One way or another it is up to you. I just think it would be nice to point out why it is awesome. And being LinkedIn product is not a good advertisement :)

**Pull request merged**
