### PR TITLE
Adding SparklingGraph to graph processing section

### PR DESCRIPTION
**Pull request by riomus**
http://sparkling.ml

### CODE REVIEW

**Comment by zero323** [comment]
@oluies, @eliasah - are you familiar with the project?

**Comment by oluies** [comment]
No, I can have a look

**Comment by zero323** [comment]
@oluies That's great :)

**Comment by oluies** [comment]
It uses spark, but is new and has only one committer. Cant see no harm in linking to it, might not be awesome but there is a lack of graph stuff for spark 

(for now I use http://uzh.github.io/signal-collect/ for this, together with Neo4J and/or DataStax Enterprise Graph )

**Comment by eliasah** [comment]
I'm not familiar with the project but it looks interesting and serious.

**Comment by zero323** [comment]
@eliasah, @oluies At your discretion. Just be sure to fix the missing full stop at the end of the line.

**Comment by zero323** [comment]
@eliasah, @oluies I am going to merge this. Despite some warning signs (a single contributor, low interest), it has some really nice features and seems to work reasonably well in my own experiments.

**Comment by zero323** [comment]
Thanks @riomus!

**Pull request merged**
