### PR TITLE
Adding StreamSets Transformer

### PR DESCRIPTION
**Pull request by jeff303**
Review copy of the tool can be provided as needed (please contact via my profile to arrange).  Thanks.

### CODE REVIEW

**Comment by eliasah** [comment]
@zero323 @oluies what are you thoughts on this ?

**Comment by oluies** [comment]
Its commercial which should be highligted.

**Comment by zero323** [comment]
I assume that none of the members actually used it in practice, am I right?

At first glance at the docs, my main concern is that the project relationship with Spark is mostly inconsequential from the user perspective.

**Comment by jeff303** [comment]
> I assume that none of the members actually used it in practice, am I right?

Sorry, what do you mean by "members" in this context?

> At first glance at the docs, my main concern is that the project relationship with Spark is mostly inconsequential from the user perspective.

It's true that Transformer tries to abstract away many of the details of Spark, but it's hardly inconsequential.  Users can still write Spark SQL expressions as part of the processing, write Scala code to manipulate the `DataFrame` objects, etc.

**Comment by zero323** [comment]
> > I assume that none of the members actually used it in practice, am I right?
> 
> Sorry, what do you mean by "members" in this context?

Sorry for the confusion @jeff303. I meant participants of this discussion which are members of [awesome-spark](https://github.com/awesome-spark) and / or have merge rights to this repository.

Traditionally we merge only the products that some of us used and  can vouch for it, with some exceptions to very popular projects.

> > At first glance at the docs, my main concern is that the project relationship with Spark is mostly inconsequential from the user perspective.
> 
> It's true that Transformer tries to abstract away many of the details of Spark, but it's hardly inconsequential. Users can still write Spark SQL expressions as part of the processing, write Scala code to manipulate the `DataFrame` objects, etc.

Let me put this in a different way - as a moderately experienced Spark user  I don't see how this could be relevant for me. I won't contribute, because it is closed sourced. I cannot analyze it for the same reason. I doesn't seem like I can take my existing Spark code and bring it to your platform (other than copying-and-pasting it into a transformer. Correct me if I missed something). Finally SQL is hardly Spark specific, so that, as far as I can tell, leaves use with Python and Scala transformers which, based on the documentation, don't seem to be central for the end user.

So assuming that at the moment internals use Spark, and tomorrow you switched to some-new-fancy-framework™ keeping API intact, it would make not practical difference for me as the potential user.

Anyway...  These are just my thoughts. This is not a judgment of quality of your project, or binding opinion for the other participants of this discussion.

@oluies @eliasah  Formal nitpick - if you decide to merge please make sure that full stop is included at the end of the line.

**Comment by eliasah** [comment]
I concur with @zero323 on this. Regardless the quality of the project, I'm not very much fan of adding projects here that I haven't tested and that I cannot test.

**Comment by jeff303** [comment]
As mentioned in the initial PR, I can provide anyone who likes it with a tarball and installation instructions.  I just can't do so via a public Github comment.

Regardless, it sounds like perhaps this isn't a right fit with the goal of this repo, since fundamentally the Spark cluster does serve as an "execution engine" of sorts for the product.  Also, it's not currently open source, though I hope one day that will change.

We do have a large set of utility classes on top of the `DataFrame` API for doing operations that may be potentially useful in a general sense (ex: reordering columns to match before performing a merge, deleting a deeply nested struct field from a DF/schema, etc.).  Once that is available as a separate, standalone library, I can create a separate PR for it.

Thanks for your time.

**Comment by eliasah** [comment]
Thanks for your understanding @jeff303 and thanks for your time as well.

**Pull request closed without merging**
