### PR TITLE
Add spark-fast-tests

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by MrPowers** [comment]
I've worked on spark-testing-base a bit and created spark-fast-tests for [these use cases](https://github.com/MrPowers/spark-fast-tests#alternatives).  spark-testing-base has a lot more features, but spark-fast-tests has some good use cases and I'd like to let the community know about this alternative.

**Comment by eliasah** [comment]
Hello @MrPowers ! Thanks for sharing. Seems like an interesting project, but I would personally wait a bit before adding it :)

**Comment by MrPowers** [comment]
@eliasah - That's fine :)  I've been able to speed up a few test suites by ~40%, but agree that the project is still immature.  I was recently added as a maintainer of the spark-testing-base project, so hopefully I can get some of the spark-fast-tests optimizations in that codebase!

**Comment by eliasah** [comment]
Oh that's great ! So will you still be working spark-fast-tests @MrPowers ? :)

**Comment by MrPowers** [comment]
I'm still going to work on spark-fast-tests @eliasah.  spark-fast-tests has a quick release cycle.  It's a little more complicated with spark-testing-base because they need to support a lot of legacy Spark versions.  I'll reopen this pull request when spark-fast-tests gets more popular.

**Comment by eliasah** [comment]
Sounds great ! I'm looking forward to adding it then @MrPowers ;)

**Comment by MrPowers** [comment]
@eliasah - I wrote a blog post that demonstrates how the spark-fast-tests `assertSmallDataFrameEquality` method is 31% faster than the `assertDataFrameEquals` in spark-testing-base: https://medium.com/@mrpowers/how-to-cut-the-run-time-of-a-spark-sbt-test-suite-by-40-52d71219773f

Not sure how to make this project more mature, but the gains are real! 😉

**Comment by eliasah** [comment]
I was watching that project. ;)

**Pull request merged**
