### PR TITLE
Add Apache DataFu to list of general purpose Spark libraries

### LINKED ISSUE #201: Consider Apache DataFu
https://github.com/apache/DataFu

### PR DESCRIPTION
**Pull request by eyala**
Resolves #201

### CODE REVIEW

**Review by zero323 — CHANGES_REQUESTED** [review]
I believe it would be better to keep format that we usually use for software projects (repo link and latest update badge).

**Comment by eyala** [comment]
Done

**Comment by eyala** [comment]
> I believe it would be better to keep format that we usually use for software projects (repo link and latest update badge).

Done

**Comment by zero323** [comment]
@eliasah @oluies Any thoughts?

**Comment by oluies** [comment]
LGTM

**Comment by zero323** [comment]
I think we could simply the description to something like

> A library of general purpose functions and UDF's.

The ASF ownership is implied by the name of the project and we typically avoid mentioning Spark in the descriptions (though it is not a hard rule)..

**Comment by eyala** [comment]
Sounds reasonable.

**Review by zero323 — APPROVED** [review]

**Comment by zero323** [comment]
Thanks @eyala, @oluies, @eliasah.
Merged.

**Pull request merged**
