### PR TITLE
[ADD] Data Analysis with Python and PySpark

### PR DESCRIPTION
**Pull request by ipcenas**
Hi,
I am Branko from Manning Publications, this new book of ours could be a good resource for the list.
What do you think?
Thanks for checking it out!

### CODE REVIEW

**Comment by zero323** [comment]
Thanks for your proposal @ipcenas. 

In general, we add only the resources that the maintainers personally recommend, so it is likely going wait for someone to read this book (cannot say if it is on anyone's reading list).

**Comment by eliasah** [comment]
I'd rather we wait till this book is not in MEAP anymore.

**Comment by oluies** [comment]
Released in february 2022 https://www.manning.com/books/data-analysis-with-python-and-pyspark

**Comment by eliasah** [comment]
I will try to read the book when I have some time...

**Pull request closed without merging**
