### PR TITLE
add sparkmagic(jupyter notebook)

### PR DESCRIPTION
**Pull request by cycorey**

### CODE REVIEW

**Comment by zero323** [comment]
I have two notes:

- Title should be less verbose. `sparkmagic` alone without ` on Jupyter(IPython Notebook)` should be enough.
- I think it would be a good idea to emphasize that it is a Livy tool.

**Comment by eliasah** [comment]
what should we do about this ? I don't want to merge as is. I'd rather applying the notes that you've mentioned.

**Comment by zero323** [comment]
@eliasah  I don't have any strong feelings about it. It looks like niche tool so I don't think we loose much by leaving it open until @cycorey decides to adjust it. Unless you really want it to be merged now and are willing to do the work.

**Comment by eliasah** [comment]
Ok then I'm not touching it.

**Comment by cycorey** [comment]
I have update the description, @zero323 thanks.

**Pull request merged**
