### PR TITLE
Add Apache Toree

### PR DESCRIPTION
**Pull request by zero323**

### CODE REVIEW

**Comment by eliasah** [comment]
beside the conflict ? I'm not sure about toree being under middleware. Why do you want to put it there ?

**Comment by zero323** [comment]
Where else would place it?

**Comment by eliasah** [comment]
I'm sorry my bad. I always think of toree as a jupyter, but it's actually a gateway to spark from jupyter. So it's ok with me !

**Comment by zero323** [comment]
Do you want to resolve the conflict? I know it is your favorite part of the Git worfklow :)

**Pull request merged**
